### PR TITLE
Uncheck bundle

### PR DESCRIPTION
**Pull request by ItIsGreg**
Added functionality to checkout indivdiual resources as well as checkout individual resources as bundles

### CODE REVIEW

**Comment by trostalski** [comment]
@ItIsGreg What functionality should be supported here?

My Understanding:
- Export all resources and bundles in one large bundle
- Export all Bundles and Resources individually

Do we need anything else?

**Comment by ItIsGreg** [comment]
> @ItIsGreg What functionality should be supported here?
> 
> My Understanding:
> 
>     * Export all resources and bundles in one large bundle
> 
>     * Export all Bundles and Resources individually
> 
> 
> Do we need anything else?

In the current implementation it is not possible to export resources individually without the bundle overhead. I think it should be possible to export resources bare. Also it was not possible to export all bundles and resources individually without reopening the export dialog for each indivdual resource/bundle.

**Comment by trostalski** [comment]
@ItIsGreg lets discuss this and then reopen, closing for now

**Comment by trostalski** [comment]
Short term Plan:

- Keep "Bundle Output" -> checked: Bundle selection, unchecked: Export selection in individual files
- Remove "Bundle Individually"
- Add "Bundle" and "Resource" Modals to Export Modal so that the two have to be exported separately

Then Merge.

Then think about additional features.
-> Export from storage selection...

**Pull request merged**
